# Generated by Django 5.0.6 on 2024-05-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportfile',
            name='custom_headers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='exportfile',
            name='fields_to_export',
            field=models.JSONField(default=list),
        ),
    ]
