# Generated by Django 5.0.6 on 2024-05-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_exportfile_custom_headers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportfile',
            name='custom_headers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
