# Generated by Django 5.0.6 on 2024-05-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_parsinglink_task_alter_exportfile_custom_headers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='brand',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='model',
            field=models.CharField(max_length=255),
        ),
    ]
