# Generated by Django 5.0.6 on 2024-05-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_alter_advertisement_brand_alter_advertisement_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportfile',
            name='fields_to_export',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price_euro',
            field=models.CharField(max_length=255),
        ),
    ]
