# Generated by Django 5.0.6 on 2024-06-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_remove_exportfile_fields_to_export_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exportfile',
            name='parsing_link',
        ),
        migrations.AlterField(
            model_name='exportfile',
            name='schedule_time',
            field=models.TimeField(),
        ),
    ]
