# Generated by Django 5.0.6 on 2024-06-05 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_proxy_remove_exportfile_parsing_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.BigIntegerField()),
                ('in_progress', models.BooleanField()),
                ('parsing_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.parsinglink')),
            ],
        ),
    ]
