# Generated by Django 5.0.6 on 2024-06-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_parsinglink_created_at_parsinglink_performed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('my_field', models.CharField(choices=[('part_name_ua', 'part_name_ua'), ('part_name_ru', 'part_name_ru'), ('part_group_name_ua', 'part_group_name_ua'), ('part_group_name_ru', 'part_group_name_ru'), ('part_site_id', 'part_site_id'), ('part_group_site_id', 'part_group_site_id'), ('symbolic_code', 'symbolic_code'), ('brand', 'brand'), ('brand_site_id', 'brand_site_id'), ('model', 'model'), ('model_site_id', 'model_site_id'), ('generation', 'generation'), ('description_ua', 'description_ua'), ('description_ru', 'description_ru'), ('label_1', 'label_1'), ('label_2', 'label_2'), ('label_3', 'label_3'), ('price_euro', 'price_euro'), ('symbolic_code_site', 'symbolic_code_site'), ('article', 'article'), ('allegro_link', 'allegro_link'), ('allegro_id', 'allegro_id'), ('allegro_price_pln', 'allegro_price_pln'), ('allegro_title', 'allegro_title'), ('vin', 'vin'), ('allegro_seller', 'allegro_seller'), ('allegro_images', 'allegro_images'), ('parsing_link', 'parsing_link'), ('exported', 'exported')], max_length=255)),
            ],
        ),
    ]
