# Generated by Django 5.0.6 on 2024-06-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_exportcsv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsinglink',
            name='task',
        ),
        migrations.AlterField(
            model_name='parsinglink',
            name='generation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parsinglink',
            name='label_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parsinglink',
            name='label_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parsinglink',
            name='label_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
