# Generated by Django 5.0.6 on 2024-06-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0013_alter_advertisement_generation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskChain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chain_ids", models.JSONField()),
                ("start_from", models.IntegerField(default=0)),
            ],
        ),
    ]
