# Generated by Django 5.0.6 on 2024-08-01 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0014_taskchain"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
