# Generated by Django 5.0.6 on 2024-08-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0015_advertisement_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
