# Generated by Django 5.0.6 on 2024-08-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0016_alter_advertisement_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
