# Generated by Django 5.0.6 on 2024-08-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0018_alter_apitoken_email_alter_apitoken_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="concurrent_requests",
            field=models.IntegerField(
                default=1, help_text="Number of concurrent requests"
            ),
        ),
    ]
