# Generated by Django 5.0.6 on 2024-08-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0019_apitoken_concurrent_requests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="concurrent_requests",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of concurrent requests"
            ),
        ),
    ]
