# Generated by Django 5.0.6 on 2024-08-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0022_exportedfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exportedfile",
            name="file",
        ),
        migrations.AddField(
            model_name="exportedfile",
            name="filepath",
            field=models.FilePathField(default="/exports", path="/exports"),
            preserve_default=False,
        ),
    ]
