# Generated by Django 5.0.6 on 2024-08-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0023_remove_exportedfile_file_exportedfile_filepath"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportedfile",
            name="filepath",
            field=models.FilePathField(path="~/alegro_parser/exports"),
        ),
    ]
