# Generated by Django 5.0.6 on 2024-08-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0024_alter_exportedfile_filepath"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportedfile",
            name="filepath",
            field=models.FilePathField(path="/code/exports"),
        ),
    ]
