# Generated by Django 5.0.6 on 2024-08-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0025_alter_exportedfile_filepath"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
