# Generated by Django 5.0.6 on 2024-08-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0026_advertisement_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
