# Generated by Django 5.0.6 on 2024-09-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0027_advertisement_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="polish_word",
            field=models.CharField(
                help_text="Example: korozji or korozji/korozja/rdza", max_length=255
            ),
        ),
    ]
